// Generated by wrangler (cf-typegen). Do not edit manually.
// Run `npm run cf-typegen` to regenerate after changing wrangler.jsonc bindings.

interface Env {
	ASSETS: Fetcher;
	NEON_AUTH_BASE_URL: string;
}
