// Generated by wrangler (cf-typegen). Do not edit manually.
// Run `npm run cf-typegen` to regenerate after changing wrangler.jsonc bindings.

interface Env {
	VITE_NEON_AUTH_URL: string;
	VITE_API_BASE_URL: string;
}
