/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ccc6fa54afc9037968b2b0907774ea34)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
